# -*- coding: utf-8 -*-
"""c105

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b_9q7LMCMC2gov8HRYcxBc7Qo_pHXLTB
"""

from google.colab import files
data_to_load=files.upload()

import csv
with open("std1.csv",newline= "")as f:
  reader=csv.reader(f)
  file_data=list(reader)
file_data.pop(0)
total_marks=0
total_entries=len(file_data)
for marks in file_data:
  total_marks+=float(marks[1])
mean=total_marks/total_entries
print("Mean is = "+str(mean))

import pandas as pd
import plotly.express as px
df=pd.read_csv("std1.csv")
fig=px.scatter(df,x="Student Number",y="Marks")
fig.update_layout(shapes=[dict(
    type='line',y0=mean,y1=mean,x0=0,x1=total_entries
)])
fig.update_yaxes(rangemode="tozero")
fig.show()

from google.colab import files
data_to_load=files.upload()



import csv
with open("std2.csv",newline= "")as f:
  reader=csv.reader(f)
  file_data=list(reader)
file_data.pop(0)
total_marks=0
total_entries=len(file_data)
for marks in file_data:
  total_marks+=float(marks[1])
mean=total_marks/total_entries
print("Mean is = "+str(mean))

import pandas as pd
import plotly.express as px
df=pd.read_csv("std2.csv")
fig=px.scatter(df,x="Student Number",y="Marks")
fig.update_layout(shapes=[dict(
    type='line',y0=mean,y1=mean,x0=0,x1=total_entries
)])
fig.update_yaxes(rangemode="tozero")
fig.show()

from google.colab import files
data_to_load=files.upload()

import csv
with open("sa1.csv",newline= "")as f:
  reader=csv.reader(f)
  file_data=list(reader)
data=file_data[0]

def mean(data):
  n=len(data)
  total=0
  for x in data:
    total+=int(x)
  mean=total/n
  return mean

squard_list=[]
for number in data:
  a=int(number)-mean(data)
  a=a**2
  squard_list.append(a)
  import math
sum=0
for i in squard_list:
  sum=sum+i
result=sum/(len(data)-1)
std_dev=math.sqrt(result)
print(std_dev)